comments/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import comment_thread, comment_delete
app_name = 'comment'

urlpatterns = [
    path('<int:id>/',comment_thread, name='thread'),
    path('<int:id>/delete',comment_delete, name='comment_delete'),
    # path('<int:pk>/delete', views.post_delete, name='post-delete'),
]

posts/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
app_name = 'posts'
urlpatterns = [
    path('', views.post_list, name='post-list'),
    path('new/', views.post_create, name='post-create'),
    path('<int:pk>/', views.post_detail, name='post-detail'),
    path('<int:pk>/edit', views.post_update, name='post-update'),
    path('<int:pk>/delete', views.post_delete, name='post-delete'),
]

user/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import register, profile
from django.contrib.auth import views as auth_views
app_name = 'users'

urlpatterns = [
    path('register/',register, name='register'),
    path('login/',auth_views.LoginView.as_view(template_name="login.html"),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name="logout.html"),name='logout'),
    path('profile/',profile,name='profile'),
]

web_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls',namespace = 'posts')),
    path('comments/', include('comments.urls',namespace = 'comments')),
    path('accounts/', include('user.urls',namespace = 'users')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from django.db import models
from django.urls import reverse
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.conf import settings
from django.utils.safestring import mark_safe
from comments.models import Comment
from django.contrib.contenttypes.models import ContentType
from markdown_deux import markdown
from .utils import get_read_time
# This is the Post model it is used as an sql database table and its atributes are its column names


def upload_loaction(instance, filename):
    return "{}/{}".format(instance.id, filename)


class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=True, default=1)
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to=upload_loaction,
                              null=True, blank=True, width_field='width_field', height_field='height_field')
    width_field = models.IntegerField(default=0)
    height_field = models.IntegerField(default=0)
    content = models.TextField()
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    read_time = models.TimeField(null = True, blank = True)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __str__(self):
        return self.title
# This method get the absolute url of a particular post from the database

    def get_absolute_url(self):
        return reverse('posts:post-detail', kwargs={'pk': self.pk})

    @property
    def comments(self):
        instance = self
        qs = Comment.objects.filter_by_instance(instance)
        return qs

    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type
# This class is used to order the mode post in web page

    class Meta:
        ordering = ['-timestamp', '-updated']

    def get_markdown(self):
        content = self.content
        markdown_text = markdown(content)
        return mark_safe(markdown_text)
def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if instance.content:
        html_string = instance.get_markdown()
        time = get_read_time(html_string)
        print(time)
        instance.read_time = time
pre_save.connect(pre_save_post_receiver,sender=Post)

posts/forms.py
from django import forms
from .models import Post
from pagedown.widgets import PagedownWidget
class PostForm(forms.ModelForm):
    content = forms.CharField(widget=PagedownWidget(show_preview=False))
    class Meta:
        model = Post
        fields = ['title', 'content', 'image']

posts/views.py
from urllib import parse
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.contrib import messages
from django.core.paginator import Paginator

from .models import Post
from .forms import PostForm
from django.db.models import Q

from django.contrib.contenttypes.models import ContentType
from comments.models import Comment
from comments.forms import CommentForm
from django.contrib.auth.decorators import login_required
# This View is used to create the post
# @param request This is common for all views and is used because in
# web we use request to do almost every thing like http Get Request and post request
# this method use the form that is created in forms.py to form a post and then save it
# if it is valid

def post_create(request):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    if not request.user.is_authenticated:
        raise Http404
    form = PostForm(request.POST or None, request.FILES)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        messages.success(request, "Successfully created")
        return HttpResponseRedirect(instance.get_absolute_url())
    elif request.method == 'POST':
        messages.error(request, "Some thing wrong happen try again later")
    context = {
        'form': form,
    }
    return render(request, 'post_form.html', context)

# this view is used for the detail view of the post


def post_detail(request, pk=None):
    instance = get_object_or_404(Post, pk=pk)
    share_string = parse.quote_plus(instance.content)
    comments = instance.comments
    # initial data for the comment form
    initial_data = {
        'content_type': instance.get_content_type,
        'object_id': instance.id
    }
    # creating and instantiating the Comment Form Object and giving it initial data to create the comment for a particular post
    comment_form = CommentForm(request.POST or None, initial=initial_data)
    if comment_form.is_valid():
        # if the form is valid the getting the content_type from the comment_form
        # getting the object id from the comment_form
        # getting the content from the comment_form
        # form that data from form creating the whole comment (Comment model)
        c_type = comment_form.cleaned_data.get('content_type')
        obj_id = comment_form.cleaned_data.get('object_id')
        content_type = ContentType.objects.get(model=c_type)
        content_data = comment_form.cleaned_data.get('content')
        parent_obj = None
        try:
            parent_id = int(request.POST.get('parent_id'))
        except:
            parent_id = None
        if parent_id:
            parent_qs = Comment.objects.filter(id=parent_id)
            if parent_qs.exists() and parent_qs.count() == 1:
                parent_obj = parent_qs.first()
        if not request.user.is_authenticated:
            messages.info(request,"Login to comment ")
            return redirect('users:login')
        new_comment, created = Comment.objects.get_or_create(
            user=request.user,
            content_type=content_type,
            object_id=obj_id,
            comentText=content_data,
            parent=parent_obj
        )
        return HttpResponseRedirect(new_comment.content_object.get_absolute_url())
    context = {
        'instance': instance,
        'share_string': share_string,
        'comments': comments,
        'comment_form': comment_form
    }
    return render(request, 'post_detail.html', context)
# This is the main view where a list of blog posts is showed to the user


def post_list(request):
    queryset_list = Post.objects.all()
    paginator = Paginator(queryset_list, 4)
    page = request.GET.get('page')
    queryset = paginator.get_page(page)
    query = request.GET.get('q')
    if query:
        queryset = Post.objects.filter(
            Q(title__icontains=query) |
            Q(content__icontains=query) |
            Q(user__first_name__icontains=query)

        )
    context = {
        'posts': queryset
    }
    return render(request, 'post_list.html', context)
# This view is used to update the content of certain post
# it takes id and request as a parameter id to determine which post to enit


def post_update(request, pk=None):
    instance = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = PostForm(request.POST or None, request.FILES, instance=instance)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            messages.success(request, "successfully updated")
            return HttpResponseRedirect(instance.get_absolute_url())
        else:
            form = PostForm(instance=instance)
            context = {
                'title': instance.title,
                'instance': instance,
                'form': form,
            }
            messages.error(request, "Something went wrong")
            return render(request, 'post_form.html', context)
    else:
        form = PostForm(instance=instance)
        context = {
            'title': instance.title,
            'instance': instance,
            'form': form,
        }
    return render(request, 'post_form.html', context)
# As the name suggest this is used to delete the post with the provided id


def post_delete(request, pk=None):
    instance = get_object_or_404(Post, pk=pk)
    if request.method == "POST" and request.user == instance.user:
        instance.delete()
        messages.success(request, 'post has been deleted successfully ')
        return redirect('posts:post-list')
    return render(request, 'confirm_delete.html', {'object': instance})

templates/base.html
{% load static %} {% load markdown_deux_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<meta http-equiv="X-UA-Compatible" content="ie=edge" />
		<title>{% block head_title %}Coder's blog {% endblock head_title %}</title>
		<link rel="stylesheet" href="{% static 'css/base.css' %}" />
		<link
			rel="stylesheet"
			href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
			crossorigin="anonymous"
		/>
		<link
			rel="stylesheet"
			href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
		/>
		{% block head_extra %} {% endblock head_extra %}
	</head>
	<style></style>
	<body>
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top mb-5">
			<div class="container">
				<a href="{% url 'posts:post-list' %}" class="navbar-brand"
					>Coder's blog</a
				>

				<button
					class="navbar-toggler collapsed"
					type="button"
					data-toggle="collapse"
					data-target="#navbarResponsive"
					aria-controls="navbarResponsive"
					aria-expanded="false"
					aria-label="Toggle navigation"
				>
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse" id="navbarResponsive" style="">
					<ul class="navbar-nav ml-auto">
						<li class="nav-item active">
							<a class="nav-link" href="{% url 'posts:post-list' %}"
								>Home
								<span class="sr-only">(current)</span>
							</a>
						</li>
						{% if user.is_authenticated %}
						<li class="nav-item">
							<a class="nav-link" href="{% url 'users:profile' %}">Profile</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
						</li>
						{% if user.is_staff or user.is_superuser %}
						<li class="nav-item">
							<a class="nav-link" href="{% url 'posts:post-create' %}"
								>New Post</a
							>
						</li>
						{% endif %} {% else %}
						<li class="nav-item">
							<a class="nav-link" href="{% url 'users:register' %}">Signup</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{% url 'users:login' %}">Login</a>
						</li>
						{% endif %}
					</ul>
					<form class="form-inline" role="search" method="GET">
						<input
							class="search js-search form-control form-control-rounded mr-sm-2"
							type="text"
							value="{{ request.GET.q }}"
							name="q"
							title="Enter search query here.."
							placeholder="Search.."
							aria-label="Search"
						/>
					</form>
				</div>
			</div>
		</nav>
		<div class="container pt-5 mt-4">
			{% if messages %} {% for message in messages %}
			<div class="alert alert-{{ message.tags }} mt-2 card col-sm-8">
				{{ message }}
			</div>
			{% endfor %} {% endif %} {% block content %} {% endblock content %}
		</div>
		<script
			src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
			integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
			crossorigin="anonymous"
		></script>
		<script
			src="http://code.jquery.com/jquery-3.3.1.min.js"
			integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
			crossorigin="anonymous"
		></script>
		<script type="text/javascript">
			$("img").addClass("img-fluid");
			$(".comment-reply-btn").click(function(event) {
				event.preventDefault();
				$(this)
					.parent()
					.next(".comment-reply")
					.fadeToggle();
			});
		</script>
	</body>
</html>

templates/comment_thread.html
{% extends "base.html" %} 
{% load crispy_forms_tags %}
{% load markdown_deux_tags %} {% block content %}
<div class="col-md-7">
  <div class="media-body">
    <div class="page-header">
    <h3 class="mt-0">{{ comment.user }}</h3>
  </div>
       <p> {{comment.comentText }}</p>
    <footer class="blockquote-footer"> {{comment.timestamp|timesince }} ago 
      {% if comment.childrens.count > 0 %} {{ comment.childrens.count }} Comments | {% endif %}</footer>
      {% if comment.user == user %} <a class="btn btn-danger" href="{% url 'comments:comment_delete' comment.id %}">Delete</a>{% endif %}
      <hr/>
    <div class="comment-reply">
      {% for child_comment in comment.childrens %}
      <div class="replies ml-4">
          <div class="page-header">
        <h3 class="mt-0">{{ child_comment.user }}</h3>
        </div>
        <p class="lead">{{child_comment.comentText }}</p>
     <footer class="blockquote-footer">via {{ child_comment.user }}| {{child_comment.timestamp|timesince }} ago</footer>
      </div>
    {% endfor %}
    <div class="comments card my-4">
        <h5 class="lead card-header">Leave a Reply </h5>
        <div class="card-body">
  <form action="." method="POST">
      {% csrf_token %}
      {{ comment_form|crispy }}
      <div class="form-group">
      <input type="hidden"  name="parent_id" value="{{ comment.id }}">
      <input type="submit" value="Reply " class="btn btn-dark">
    </div>
    </form>
    </div>
    </div>
    <hr/>
</div>
</div>
</div>
{% endblock content %}

templates/confirm_delete.html
{% extends "base.html" %} 
{% load crispy_forms_tags %}
{% load markdown_deux_tags %} {% block content %}
<div class="col-sm-6  card  mt-5 mb-5 pt-2 pb-2 pr-2 pl-2col-sm-offset-3">
    <h1>Confirm delete</h1>
    <form method="POST">{% csrf_token %}
       <h2> Are you sure you want to delete "{{object.comentText}}" </h2>
       ,<input type="submit" value="Confirm" class="btn btn-outline-danger">
      <a href="{{ object.get_absolute_url }}" class="btn btn-outline-success">Cancel</a>
    </form>
    <hr/>
</div>

{% endblock content %}

templates/login.html
{% extends "base.html" %}
{% load crispy_forms_tags  %}
{% block content%}
<div class="col-sm-8 mt-5 card">
<h1>Log in</h1>
<form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" class="btn btn-lg btn-block btn-dark" value="Login">
</form>
<small class="text-muted mt-2 mb-2">Don't have an account create <a href="{% url 'users:register' %}"> here</a></small>
</div>
{% endblock content %}

templates/logout.html
{% extends "base.html" %}
{% block content%}
<div class="col-sm-8 mt-5 pt-5 pb-5 pl-3 pr-3 card">
<h1>You have been logged out</h1>
<p> Log in again <a href="{% url 'users:login' %}">here</a></p>
</div>
{% endblock content %}

templates/navigation.html
{% extends "base.html" %} {% block navigation %}

templates/post_detail.html
{% extends "base.html" %} 
{% load crispy_forms_tags %}
{% load markdown_deux_tags %}
{% block content %}
<div class="col-sm-8 mt-2 mb-5 pt-2 pb-2 pr-2 pl-2 col-sm-offset-3">
  <div class="caption">
    {% if user == instance.user %}
    <a href="{% url 'posts:post-delete' instance.id %}" class="btn btn-danger"> Delete </a>
    <a href="{% url 'posts:post-update' instance.id %}" class="btn btn-secondary">Edit Post</a>
    {% endif %}
    <h3 class="mt-4">
      {{ instance.title }}
    </h3>
    {% if instance.image %}

    <img src="{{ instance.image.url }}" class="img-fluid" />
    {% endif %}
    <p class="text-muted ">Read  Time : {{ instance.read_time|time:'i' }} min</p>
    <p class="text-muted">Posted on {{ instance.timestamp }} </p>
    {% if instance.user %}
    <p class="lead"> Posted by <a href=""> {{instance.user }} </a></p>
    {% endif %} Share on
    <a
      class="twitterlink"
      href="https://twitter.com/home?status={{ object.text }}%20{{
        request.build_absolute_uri
      }}"
    >
      Twitter
    </a>
    <a
      class="glink"
      href="https://plus.google.com/share?url=http://codingforentrepreneurs.com"
    >
      Google+</a
    >
    <a
      class="linkedinlink"
      href="https://www.linkedin.com/shareArticle?mini=true&url={{
        request.build_absolute_uri
      }}&title={{ post.text }}20me!&source={{ request.build_absolute_uri }}"
    >
      Linkedin
    </a>

    <p id="content" class="content-markdown mt-2 mb-2 mr-2 ml-2 lead">
      {{ instance.content|markdown|linebreaks }}
    </p>
    
    <div class="comments card my-4">
      <h5 class="lead card-header">Leave a Comment </h5>
      <div class="card-body">
      <form action="." method="POST">
          {% csrf_token %}
          <div class="form-group">
          {{ comment_form|crispy }}
          <input type="submit" value="Comment" class="btn btn-outline-dark">
        </div>
        </form>
      </div>
    </div>
      {% for comment in comments %}

        <div class="media mb-4">
          <div class="media-body">
            <div class="page-header">
            <h4 class="mt-0 ml-2"> {{ comment.user }}</h4>
          </div>
          
           <p class = "ml-2 mr-2 ">{{comment.comentText }}</p>

        <footer class="blockquote-footer"> {{comment.timestamp|timesince }} ago 
          {% if comment.childrens.count > 0 %} {{ comment.childrens.count }} Comments | {% endif %}
          <a class="comment-reply-btn" href="#">Reply</a> |
          <a  href="{{ comment.get_absolute_url }}">Thread</a><br>
          {% if user ==  comment.user %} 
          <a href="{% url 'comments:comment_delete' comment.id %}" class="pull-right"><span class="badge badge-danger mt-2 mb-2">Delete</span></i></a> 
          {% endif %}
          
        </footer>
        <div class="comment-reply mt-4" style="display: none">
          {% for child_comment in comment.childrens %}
          <div class="media-body ml-5">
            <div class="page-header">
           <h4 class="mt-0"> {{ child_comment.user }}</h4>
          </div>
           {{child_comment.comentText }}
         <footer class="blockquote-footer"> {{child_comment.timestamp|timesince }} ago</footer>
          </div>
        {% endfor %}
        <div class="comments card my-4">
            <h5 class="lead card-header">Leave a Reply </h5>
            <div class="card-body">
      <form action="." method="POST">
          {% csrf_token %}
          <div class="form-group">
          {{ comment_form|crispy }}
          <input type="hidden"  name="parent_id" value="{{ comment.id }}">
          <input type="submit" value="Reply " class="btn btn-dark">
        </div>
        </form>
        </div>
        </div>
        </div>
    </div>
  </div>
      {% endfor %}
  
  </div>
</div>
{% endblock content %}

templates/post_form.html
{% extends 'base.html' %} {% load static %} 
{% load crispy_forms_tags %}
{% block head_extra %}
{{ form.media }}
{% endblock head_extra %} {% block content %}
<style>

.wmd-panel {
	margin-left: 0px !important;
}</style>
<div class="row">
<div class="col-sm-6 card">
  <h1>Preview</h1>
  <div class="content-preview">
    <h3 id="preview-title"></h3>
    <p id="preview-content"></p>
  </div>
</div>

<div class="col-sm-4">
  <h1>Form</h1>
  <form method="POST" action="" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" class="btn btn-primary" value="create Post" />
  </form>
</div>
</div>
<script
  src="http://code.jquery.com/jquery-1.12.2.min.js"
  integrity="sha256-lZFHibXzMHo3GGeehn1hudTAP3Sc0uKXBXAzHX1sjtk="
  crossorigin="anonymous"
></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.min.js"></script>
<script type="text/javascript">
  let titleItem = $("#id_title");
  let contentItem = $("#id_content");
  function setTitle(value) {
    let titleValue = value;
    $("#preview-title").text(titleValue);
  }
  setTitle(titleItem.val());
  titleItem.keyup(function() {
    let titleInputText = $(this).val();
    setTitle(titleInputText);
  });

  function setContent(value) {
    let markedContent = marked(value);
    $("#preview-content").html(markedContent);
    $("#preview-content img").each(function() {
      $(this).addClass("img-fluid");
    });
  }
  setContent(contentItem.val());
  contentItem.keyup(function() {
    let newValue = $(this).val();
    setContent(newValue);
  });
</script>
{% endblock %}

templates/post_list.html
{% extends "base.html" %}
{% load markdown_deux_tags %}
{% block content %}
{% load static %}

<div class="row mt-2">
  <div class="col-sm-8">
  {% for post in posts %}
  <div class="card  mt-2 mb-2 pl-3 pr-3">
        <div class="page-header">
          <a href="{{ post.get_absolute_url }}"  style="color:black"> <h2> {{post.title}}</h2></a>
        </div>

         <p class="text-muted" >
        {% if post.user %}
        {% if post.user.is_staff or post.user.is_admin %}
        Posted by <span class="badge badge-pill badge-info">Admin</span><a href=""> {{ post.user }} </a> 
        {% else %}
        Posted by <a href=""> {{ post.user }} </a>
        {% endif %}
        {% endif %} on {{ post.timestamp }}</p>
        {% if post.image %}
        <img src="{{ post.image.url }}" class="img-fluid ml-2 mr-4 mt-2 mb-0" />
        {% endif %} 
        <p id="content mt-0" class="content-markdown">
          {{ post.content|markdown |linebreaks|truncatechars_html:400 }}
          <a href="{{ post.get_absolute_url }}">(more) </a>
        </p>
    </div>
    {% endfor %}
</div> <!--end of the coloumn first  -->
  <div class="col-sm-4 mt-2" id="leftCol">
    <div class="media card my-4"
    style="position:sticky"
    >
      <p class="card-header">Recent Posts</p>
      <div class="list-group">
        {% for post in posts %}
          <a href="{{ post.get_absolute_url }}" class="list-group-item list-group-item-action">
            <div class="d-flex w-100 justify-content-between">
              <h5 class="mb-1">{{ post.title }}</h5>
              <small>{{ post.timestamp|timesince }} ago </small>
            </div>
            <p class="mb-1">{{ post.content|truncatechars_html:80 }}</p>
            <small>{{ post.user }}</small>
          </a>
          {% endfor %}
        </div>
    </div>
    </div><!-- end of the second column that is sidebar -->

  
  <div class="pagination mb-5 mt-5 col-sm-6">
    <ul class="pagination justify-content-end">
      {% if posts.has_previous %}
      <li class="page-item"><a href="?page=1" class="page-link ml-2 mr-2 btn btn-dark">&laquo; previous</a></li>
      <li class="page-item"><a href="?page={{ posts.previous_page_number }} " class="page-link ml-2 mr-2 btn btn-dark">{{ posts.previous_page_number }}</a></li>
      {% endif %}

      <li class="page-item active"><a href="?page={{ posts.number }}" class="page-link mr-2 ml-2 btn btn-dark">  {{ posts.number }}</a></li>
      {% if posts.has_next %}
      <li class="page-item"><a href="?page={{ posts.next_page_number }}" class="page-link mr-2 ml-2 btn btn-dark">{{ posts.next_page_number }} </a></li>
      {% endif %}
      <li class="page-item"><a href="?page={{ posts.paginator.num_pages }}" class="page-link btn btn-dark">last &raquo;</a> </li>
    </ul>
  </div>
</div>
<script
          src="http://code.jquery.com/jquery-3.3.1.min.js"
          integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
          crossorigin="anonymous"
        ></script>
        <script type="text/javascript">
          $("img").addClass("img-fluid");
        </script>
{% endblock content %}

templates/profile.html
{% extends "base.html" %}
{% load crispy_forms_tags  %}
{% block content%}
<div class="col-sm-8 card mt-5 pt-2 pl-2 pr-2 pb-2">
    <h2 class="mt-2">{{user.username}} </h2>
    <p>{{ user.email }}</p>
<form action="" method="POST">{% csrf_token %}
    <legend class="border-bottom mb-4">
        Profile info
    </legend>
    {{ update_form|crispy }}
    <input type="submit" value="Update" class="btn btn-outline-dark mb-4">
</form>
</div>
{% endblock content %}

templates/register.html
{% extends "base.html" %}
{% load crispy_forms_tags  %}
{% block content%}
<div class="col-sm-8 card mt-5 pt-4">
    
<form action="" method="POST" class="form-signin">{% csrf_token %}
        <h1 class="h3 mb-3 font-weight-normal">Sign Up</h1>
    {{ form.username|as_crispy_field}}
    {{ form.email|as_crispy_field }}
    {{ form.password1|as_crispy_field }}
    {{ form.password2|as_crispy_field }}
    <input type="submit" value="Sign Up" class="btn btn-lg btn-block btn-dark">
</form>
<small class="text-muted mt-2 mb-2">Already have an account Login<a href="{% url 'users:login' %}"> here</a></small>
</div>
{% endblock content %}